"""Initial migration

Revision ID: 47c9f9669e21
Revises: 
Create Date: 2025-02-18 18:33:47.323741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47c9f9669e21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('email', table_name='user')
    #op.drop_index('username', table_name='user')
    #op.drop_table('user')
    #op.drop_table('rig_component_association')
    #op.drop_table('manufacturer')
    #op.drop_table('component_type')
    #op.drop_table('status')
    #op.drop_table('rigging')
    #op.drop_table('component')
    #op.drop_index('name', table_name='role')
    #op.drop_table('role')
    #op.drop_table('user_roles')
    #op.drop_table('rig')
    #op.drop_table('rigging_type')
    #op.drop_table('model')
    #op.drop_table('size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('size', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('manufacturer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], name='model_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rigging_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rig',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rig_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('current_aad_jumps', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_roles_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_roles_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=True)
    op.create_table('component',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serial_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dom', sa.DATE(), nullable=False),
    sa.Column('size_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumps', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aad_jumps_on_mount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_type.id'], name='component_ibfk_1'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name='component_ibfk_5'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='component_ibfk_2'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='component_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rigging',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('serial_numbers', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rig_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('component_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('rigger_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_rigging_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='rigging_ibfk_1'),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name='rigging_ibfk_2'),
    sa.ForeignKeyConstraint(['rigger_id'], ['user.id'], name='rigging_ibfk_3'),
    sa.ForeignKeyConstraint(['type_rigging_id'], ['rigging_type.id'], name='rigging_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('component_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_type', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('manufacturer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rig_component_association',
    sa.Column('rig_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='rig_component_association_ibfk_1'),
    sa.ForeignKeyConstraint(['rig_id'], ['rig.id'], name='rig_component_association_ibfk_2'),
    sa.PrimaryKeyConstraint('rig_id', 'component_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
